### ISSUE TITLE
Handling of empty files

### ISSUE THREAD

**Issue by artemis-beta** [Sygmei/11Zip#13]
I accidentally stumbled across this issue when downloading a git repository with a `.gitkeep` file. This file is an empty file added to an empty directory to keep it in the repository. When `11zip` tries to extract such a file the following is thrown:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```
by commenting various parts of the code I was able to narrow this down to the `_extractFile` method running on the empty file.

I am opening this as an issue because I do not know the best way of handling this such that the solution benefits all. For my own project I can just change:
```c++
_extractFile(zipFile, filename, currentFile.string());
```
to:
```c++
try {
    _extractFile(zipFile, filename, currentFile.string());
} catch(std::logic_error&) {
    continue;
}
```
however this is potentially dangerous as if `std::logic_error` is thrown for another reason it masks the issue, and if this is thrown for a file the user does want to keep they will have no way of knowing there was a failure for the given file.

**Comment by Sygmei** [comment]
Latest commit should fix crash on empty files, let me know if that works for you :)
https://github.com/Sygmei/11Zip/commit/94a125161e4acab2638d8becd99af352d515b793

**Comment by artemis-beta** [comment]
Worked fine with what I was working on so happy to close this, thanks!
