### ISSUE TITLE
it is working with password?

### ISSUE THREAD

**Issue by alyfreym** [Sygmei/11Zip#15]
How to unzip file with protected via password?

**Comment by Sygmei** [comment]
Feature is not currently available, I'll try to work on it

**Comment by Sygmei** [comment]
Latest commit should allow you to pass a password to extract files : https://github.com/Sygmei/11Zip/commit/e68e20d9438b58f2c50ea42854f5f97256554a57

**Comment by alyfreym** [comment]
Done
