### ISSUE TITLE
Unzip only mode

### ISSUE THREAD

**Issue by tim-gromeyer** [Sygmei/11Zip#19]
Hello,
I have a question: Is there a plan for a unzip only mode?

I already have defined `MZ_DECOMPRESS_ONLY`:

```cmake
cmake_policy(SET CMP0077 NEW)

set(MZ_LIBCOMP OFF)
set(MZ_PKCRYPT OFF)
set(MZ_WZAES OFF)
set(MZ_OPENSSL OFF)
set(MZ_LIBBSD OFF)
set(MZ_SIGNING OFF)

set(MZ_DECOMPRESS_ONLY ON)

add_subdirectory(11Zip)
```

Some of these variables like `MZ_PKCRYPT` and `MZ_ZLIB`get overriden by 11Zip.

I would like to turn them of since the description ob `MZ_ZLIB` says it's used for compression but I just need decompression: `MZ_ZLIB, Enables ZLIB compression`

**Comment by Sygmei** [comment]
This would be possible, do you to try to contribute to the project and make a pull request ?

**Comment by tim-gromeyer** [comment]
I'll give it a try!
