### ISSUE TITLE
Installation Fail on VS2019 16.6.5 via cmake 3.17.3

### ISSUE THREAD

**Issue by snapp1** [Sygmei/11Zip#2]
@Sygmei Hello! Thanks for sharing the library. 
I git cloned to my C disk via git bash. Then these steps are done:
```
C:\11Zip\minizip> cmake CMakeLists.txt
C:\11Zip>         cmake CMakeLists.txt
```
![image](https://user-images.githubusercontent.com/19713326/88272062-f22a4180-ccf9-11ea-8b9e-c22ff922826e.png)
This one is failing:
![image](https://user-images.githubusercontent.com/19713326/88272121-079f6b80-ccfa-11ea-9b5a-514467ac3283.png)

Well, I have opened minizip.sln in minizip folder. VS opens it and builds it. But as soon as I create main there and try to include #include "../unzipper.cpp" to use its inner functions, VS gives errors. At first, all the includes are becoming broken 
![image](https://user-images.githubusercontent.com/19713326/88271828-98297c00-ccf9-11ea-9131-d7d91a00fdc4.png)
Source.cpp is just these 5 lines:
```
#include "../unzipper.cpp"

int main()
{
	return 0;
}
```
What can I do to proceed with the installation? 
Thank you!

**Comment by snapp1** [comment]
**Update:** 
I changed 
```
cmake_minimum_required(VERSION 2.8)
cmake_policy(SET CMP0015 NEW)

project(elzip)

file(GLOB PG_LZIP src/*.h)
file(GLOB HD_LZIP src/*.c)

add_library(elzip ${PG_LZIP} ${HD_LZIP})
```
to 
```
cmake_minimum_required(VERSION 2.8)
cmake_policy(SET CMP0015 NEW)

project(elzip)

file(GLOB PG_LZIP minizip/src/*.h)
file(GLOB HD_LZIP minizip/src/*.c)

add_library(elzip ${PG_LZIP} ${HD_LZIP})
```
So this error does not appear. 
```
CMake Error at CMakeLists.txt:9 (add_library):
  No SOURCES given to target: elzip
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
But still, when I try to import elzip.cpp to elzip.sln, I mean through Solution Explorer adding it to sources, it fails on including all files. I fell I am doing something wrong.

**Comment by snapp1** [comment]
Can you please write short guide on how to use your library? Particularly unzipping .zip into a folder. Thank you!

**Comment by Sygmei** [comment]
Hey there ! Thanks for writing this issue 👍 
This repository was a bit outdated so I updated it, the new source should work better so you can try to download it again.
I also created a [Getting Started](https://github.com/Sygmei/11Zip/wiki/Getting-started) guide with some instructions, please tell me if it was useful and if I could improve it 😄

**Comment by snapp1** [comment]
Amazing, thank you so much for the guide! Works fine and unzips the .zip archive into a folder!
