### ISSUE TITLE
Is this for only 1 format or can it do multiple?

### ISSUE THREAD

**Issue by Noscka** [Sygmei/11Zip#26]
I need a library that can extract rar, zip and 7z. so just wanted to see if this is the one

**Comment by Sygmei** [comment]
This library only handles zip format as it uses minizip under the hood

You might be looking for something like this : https://github.com/stonewell/lib7zip

Or using lib7z directly which handles a lot of formats

**Comment by Noscka** [comment]
Ah great, thank you very much
