### ISSUE TITLE
This library is too awesome

### ISSUE THREAD

**Issue by MacroMelon** [Sygmei/11Zip#27]
I simply cannot describe how ecstatic I am that this library exists. I had a simple requirement: I needed to unzip a file downloaded from a server in my app. I searched for MONTHS. Yes, Months. Zlib? After finally getting it to compile I realise it's meant for streams and not archives. Minizip? None of the repositories I found worked, even after going through their code and making changes to my build system they just simply wouldn't link properly (I tried my best :( I'm a mediocre programmer)

This was extremely frustrating as this unzipping thing was just a minor yet necessary part of my app, and I had a lot more and bigger things to worry about. Having to write my own zipping library uisng zlib was just out of the question for me.

So you can imagine my elation when I discovered this, changed literally 3 things on my end, and it worked perfectly. Also I now understand why you called it 11 for the atomic number of sodium as described in the readme.

@Sygmei , I salute you and you have my deepest respect. From the bottom of whats left of my heart after all that searching, Thank You.

(Sorry I opened this as an issue although it's not actually an issue, I just really needed to show you how helpful this has been)

**Comment by Sygmei** [comment]
Hey there ! Seems we went through the same path haha, glad my frustration could become useful in the end :)
