### ISSUE TITLE
LNK2019 in elzip.lib (from unzipper.obj) - link to an unallowed ext symbol

### ISSUE THREAD

**Issue by scriptSQD** [Sygmei/11Zip#4]
I wonder if the repo is still alive in any way, but can you help me with the thing? Compiler drops the following, I've built the library successfully, there were no errors and it doesn't seem to be my fault in any way:
```
elzip.lib(unzipper.obj) : error LNK2019: unresolved external symbol unzOpen64 referenced in function "public: bool __cdecl ziputils::unzipper::open(char const *)" (?open@unzipper@ziputils@@QEAA_NPEBD@Z).
elzip.lib(unzipper.obj) : error LNK2019: unresolved external symbol unzClose referenced in function "public: void __cdecl ziputils::unzipper::close(void)" (?close@unzipper@ziputils@@QEAAXXZ).
elzip.lib(unzipper.obj) : error LNK2019: unresolved external symbol unzGetGlobalInfo64 referenced in function "private: void __cdecl ziputils::unzipper::readEntries(void)" (?readEntries@unzipper@ziputils@@AEAAXXZ).
elzip.lib(unzipper.obj) : error LNK2019: unresolved external symbol unzGoToNextFile referenced in function "private: void __cdecl ziputils::unzipper::readEntries(void)" (?readEntries@unzipper@ziputils@@AEAAXXZ).
elzip.lib(unzipper.obj) : error LNK2019: unresolved external symbol unzLocateFile referenced in function "public: bool __cdecl ziputils::unzipper::openEntry(char const *)" (?openEntry@unzipper@ziputils@@QEAA_NPEBD@Z).
elzip.lib(unzipper.obj) : error LNK2019: unresolved external symbol unzGetCurrentFileInfo64 referenced in function "public: unsigned int __cdecl ziputils::unzipper::getEntrySize(void)" (?getEntrySize@unzipper@ziputils@@QEAAIXZ).
elzip.lib(unzipper.obj) : error LNK2019: unresolved external symbol unzOpenCurrentFile referenced in function "public: bool __cdecl ziputils::unzipper::openEntry(char const *)" (?openEntry@unzipper@ziputils@@QEAA_NPEBD@Z).
elzip.lib(unzipper.obj) : error LNK2019: unresolved external symbol unzCloseCurrentFile referenced in function "public: void __cdecl ziputils::unzipper::closeEntry(void)" (?closeEntry@unzipper@ziputils@@QEAAXXZ).
elzip.lib(unzipper.obj) : error LNK2019: unresolved external symbol unzReadCurrentFile referenced in function "public: class ziputils::unzipper & __cdecl ziputils::unzipper::operator>>(class std::basic_ostream<char,struct std::char_traits<char> > &)" (??5unzipper@ziputils@@QEAAAEAV01@AEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z).
\prog.exe : fatal error LNK1120: unresolved external elements: 9
```

**Comment by Sygmei** [comment]
How did you integrate elzip into your project ? Do you import the [`CMakeLists.txt`](https://github.com/Sygmei/11Zip/blob/master/CMakeLists.txt) with `add_subdirectory` ?
The error points out to your program not linking minizip dependency

**Comment by scriptSQD** [comment]
I actually didn't. I will get home and try that

**Comment by scriptSQD** [comment]
Btw, why would I need that if I compiled your library with cmake myself and now just include built elzip.lib

**Comment by Sygmei** [comment]
Your probably need `minizip.lib` as well, I never tested separate compilation, it was made to be integrated with the `add_subdirectory` pattern

**Comment by scriptSQD** [comment]
Oh, ok I got it, will try and give you some feedback on it... I wonder why this kind of a famous and mighty language doesn't have a simple library for working with archives...

**Comment by scriptSQD** [comment]
> Your probably need `minizip.lib` as well, I never tested separate compilation, it was made to be integrated with the `add_subdirectory` pattern

k, I'm dumb, can you share the example, how should the part of my CMakeLists look like?

**Comment by scriptSQD** [comment]
Reporting everything is fine right now, I just included compiled minizip.lib itself in my CMakeLists and everything seems to work fine! Nice library, btw

**Comment by Sygmei** [comment]
Glad it works, I'm closing this issue, feel free to re-open it if you encounter the problem again :)

**Comment by scriptSQD** [comment]
> Glad it works, I'm closing this issue, feel free to re-open it if you encounter the problem again :) 

Yeah, thanks! Forgot to close it myself
