### ISSUE TITLE
ZipFolder is not working

### ISSUE THREAD

**Issue by SurgeonsLab** [Sygmei/11Zip#5]
elz::zipFolder(std::string folderName, std::string zipTarget = "");

There is novoid for zipfolder

**Comment by Sygmei** [comment]
This function is not implemented currently, if you need it I can try to implement it

**Comment by SurgeonsLab** [comment]
@Sygmei Thanks for your reply. 

extractZip is working perfectly. But I also need zipFolder. If you implementing it. 
it will be nice really. Thanks

**Comment by Sygmei** [comment]
`zipFolder` is now implemented : https://github.com/Sygmei/11Zip/commit/0f71541909a35a3a311e87576fea6af709e2b15b
And also documented on the [`README.md`](https://github.com/Sygmei/11Zip#elzzipfolder)
If you have any problem with this function, feel free to comment on this issue or reopen another one :)

**Comment by SurgeonsLab** [comment]
Yes Working perfectly. Thanks @Sygmei
